const SHOP_DATA = [
  {
    id: 1,
    order: 1,
    title: 'Mac',
    routeName: 'shop/buy-mac',
    motto: "If you can dream it,\nMac can do it.",
    imageUrl: "/images/category/Mac.JPG",
    videoUrl: "/videos/Mac.mp4",

    items: [
      {
        id: 1,
        name: 'MacBook Air',
        imageUrl: '/images/storePages/buyMac/mac-card-40-macbook-air-13-15-202306.JPG',
        basePrice: 899,
        giftCard: true,
        giftCardPrice: 150,
        newPrice: false,
      },
      {
        id: 2,
        name: 'MacBook Pro',
        imageUrl: '/images/storePages/buyMac/mac-card-40-macbookpro-14-16-202310_GEO_US.JPG',
        basePrice: 1499,
        giftCard: true,
        giftCardPrice: 150,
        newPrice: false,
      },
      {
        id: 3,
        name: 'iMac',
        imageUrl: '/images/storePages/buyMac/mac-card-40-imac-24-202310.JPG',
        basePrice: 1249,
        giftCard: true,
        giftCardPrice: 150,
        newPrice: false,
      },
      {
        id: 4,
        name: 'Mac mini',
        imageUrl: '/images/storePages/buyMac/mac-card-40-mac-mini-202301.JPG',
        basePrice: 499,
        giftCard: true,
        giftCardPrice: 100,
        newPrice: false,
      },
      {
        id: 5,
        name: 'Mac Studio',
        imageUrl: '/images/storePages/buyMac/mac-card-40-mac-studio-202306.JPG',
        basePrice: 1799,
        giftCard: false,
        giftCardPrice: null,
        newPrice: false,
      },
      {
        id: 6,
        name: 'Studio Display',
        imageUrl: '/images/storePages/buyMac/mac-card-40-studio-display-202203.JPG',
        basePrice: 1499,
        giftCard: false,
        giftCardPrice: null,
        newPrice: false,
      },
      {
        id: 7,
        name: 'Mac Pro',
        imageUrl: '/images/storePages/buyMac/mac-card-40-mac-pro-202306.JPG',
        basePrice: 6599,
        giftCard: false,
        giftCardPrice: null,
        newPrice: false,
      },
      {
        id: 8,
        name: 'Pro Display XDR',
        imageUrl: '/images/storePages/buyMac/mac-card-40-mac-pro-display-202108.JPG',
        basePrice: 4599,
        giftCard: false,
        giftCardPrice: null,
        newPrice: false,
      }
    ],
  },
  {
    id: 2,
    order: 2,
    title: 'iPad',
    routeName: 'shop/buy-ipad',
    motto: "Touch, draw, and type\non one magical device.",
    imageUrl: "/images/category/iPad.JPG",
    videoUrl: "/videos/iPad.mp4",
    items: [
      {
        id: 1,
        name: 'iPad Pro',
        imageUrl: '/images/storePages/buyiPad/ipad-card-40-pro-202405.JPG',
        basePrice: 899,
        giftCard: true,
        giftCardPrice: 100,
        newPrice: false,
      },
      {
        id: 2,
        name: 'iPad Air',
        imageUrl: '/images/storePages/buyiPad/ipad-card-40-air-202405.JPG',
        basePrice: 549,
        giftCard: true,
        giftCardPrice: 100,
        newPrice: false,
      },
      {
        id: 3,
        name: 'iPad',
        imageUrl: '/images/storePages/buyiPad/ipad-card-40-ipad-202405.JPG',
        basePrice: 329,
        giftCard: false,
        giftCardPrice: null,
        newPrice: true,
      },
      {
        id: 4,
        name: 'iPad mini',
        imageUrl: '/images/storePages/buyiPad/ipad-card-40-ipad-mini-202109.JPG',
        basePrice: 449,
        giftCard: false,
        giftCardPrice: null,
        newPrice: false,
      },
    ],
  },
  {
    id: 3,
    order: 3,
    title: 'iPhone',
    routeName: 'shop/buy-iphone',
    motto: "Designed to be loved.",
    imageUrl: "/images/category/iPhone.JPG",
    videoUrl: "/videos/iPhone.mp4",
    
    items: [
      {
        id: 1,
        name: "iPhone 16 Pro & iPhone 16 Pro Max",
        imageUrl: "/images/storePages/buyiPhone/iphone-card-40-iphone16prohero-202409.JPG",
        basePrice: 999,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 2,
        name: "iPhone 16 & iPhone 16 Plus",
        imageUrl: "/images/storePages/buyiPhone/iphone-card-40-iphone16hero-202409.JPG",
        basePrice: 799,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 3,
        name: "iPhone 15 & iPhone 15 Plus",
        imageUrl: "/images/storePages/buyiPhone/iphone-card-40-iphone15hero-202309.JPG",
        basePrice: 699,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 4,
        name: "iPhone 14 & iPhone 14 Plus",
        imageUrl: "/images/storePages/buyiPhone/iphone-card-40-iphone14-202209.JPG",
        basePrice: 599,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 5,
        name: "iPhone SE",
        imageUrl: "/images/storePages/buyiPhone/iphone-card-40-iphonese-202203.JPG",
        basePrice: 429,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 6,
        name: "Explore all iPhone accessories",
        imageUrl: "/images/storePages/buyiPhone/iphone-card-40-accessories-202409.JPG",
        basePrice: null,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      }
    ]
  },
  {
    id: 4,
    order: 4,
    title: 'Apple Watch',
    routeName: 'shop/buy-watch',
    motto: "To wear it is to love it.",
    imageUrl: "/images/category/watch.JPG",
    videoUrl: "/videos/watch.mp4",
    items: [
      {
        id: 1,
        name: 'Apple Watch Series 10',
        imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-s10-202409.JPG',
        basePrice: 399,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 2,
        name: 'Apple Watch Ultra 2',
        imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-ultra2-202409.JPG',
        basePrice: 799,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 3,
        name: 'Apple Watch SE',
        imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-se-202409.JPG',
        basePrice: 249,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 4,
        name: 'Apple Watch Hermès Series 10',
        imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-hermes-202409.JPG',
        basePrice: 1249,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 5,
        name: 'Apple Watch Hermès Ultra 2',
        imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-hermes-ultra-202409.JPG',
        basePrice: 1399,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 6,
        name: 'Explore all Apple Watch accessories.',
        imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-acc-202409.JPG',
        basePrice: null,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: null,
      },
    ],
  },
  {
    id: 5,
    order: 5,
    title: 'Apple Vision Pro',
    imageUrl: "/images/category/visionPro.JPG",
    videoUrl: "/videos/vision4.mp4",
    routeName: 'shop/buy-vision',
    items: [
      {
        id: 1,
        name: 'Apple Vision Pro',
        imageUrl: '/images/storePages/buyVisionPro/vision-pro-card-66-vision-pro-202401.JPG',
        price: 3499,
      },
      {
        id: 2,
        name: 'ZEISS Optical Inserts',
        imageUrl: '/images/storePages/buyVisionPro/vision-pro-card-40-zeiss-optical-202401.JPG',
        price: 99,
      },
      {
        id: 3,
        name: 'Explore all Vision Pro accessories.',
        imageUrl: '/images/storePages/buyVisionPro/vision-pro-card-40-accessories-202401.JPG',
        price: null,
      }
    ],
  },
  {
    id: 6,
    order: 6,
    title: 'AirPods',
    routeName: 'airpods',
    motto: "A magical connection to your devices.",
    imageUrl: "/images/category/AirPods.JPG",
    videoUrl: "/videos/AirPods.mp4",
    items: [
      {
        id: 1,
        name: 'AirPods 4',
        imageUrl: '/images/productPages/airPods/compare_airpods_4__fy4e25bzx1u2_small_2x.JPG',
        basePrice: 129,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 2,
        name: 'AirPods 4',
        imageUrl: '/images/productPages/airPods/compare_airpods_4_noise_cancellation__fnt5kzpmite2_small_2x.JPG',
        basePrice: 179,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      },
      {
        id: 3,
        name: 'AirPods Pro 2',
        imageUrl: '/images/productPages/airPods/compare_airpods_pro_2__c3r137ebxwae_small.JPG',
        basePrice: 249,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 4,
        name: 'AirPods Max',
        imageUrl: '/images/productPages/airPods/compare_airpods_max__b14s2x6q07rm_small_2x.JPG',
        basePrice: 549,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: true,
      }
    ],
  },
  {
    id: 7,
    order: 7,
    title: 'AirTag',
    routeName: 'airtag',
    motto: "A magical connection to your devices.",
    imageUrl: "/images/category/AirTag.JPG",
    videoUrl: null,
    items: [
      {
        id: 1,
        name: '',
        imageUrl: '',
        price: 325,
      },
      {
        id: 2,
        name: '',
        imageUrl: '',
        price: 20,
      },
      {
        id: 3,
        name: '',
        imageUrl: '',
        price: 25,
      },
      {
        id: 4,
        name: '',
        imageUrl: '',
        price: 25,
      },
      {
        id: 5,
        name: '',
        imageUrl: '',
        price: 40,
      },
      {
        id: 6,
        name: '',
        imageUrl: '',
        price: 25,
      },
    ],
  },
  {
    id: 8,
    order: 8,
    title: 'Apple TV 4K',
    routeName: 'apple-tv-4k',
    motto: "The Apple experience. Cinematic in every sense.",
    imageUrl: "/images/category/TV.JPG",
    videoUrl: "/videos/Apple-TV-4K.mp4",
    items: [
      {
        id: 1,
        name: 'Apple TV 4K',
        imageUrl: '/images/productPages/appleTV/hero_tv_remote__da02803g5doy_small_2x.JPG',
        basePrice: 129,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      }
    ],
  },
  {
    id: 9,
    order: 9,
    title: 'HomePod',
    routeName: 'homepod',
    motto: "Speakers of the house.",
    imageUrl: "/images/category/HomePod.JPG",
    items: [
      {
        id: 1,
        name: 'HomePod',
        basePrice: 299,
        giftCard: false,
        imageUrl: null,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 2,
        name: 'HomePod MINI',
        basePrice: 99,
        giftCard: false,
        imageUrl: null,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      }
    ],
    itemImageUrl: '/images/productPages/hero__ernd10zm1dsi_large.JPG',
  },
  {
    id: 10,
    order: 10,
    title: 'Accessories',
    motto: "Mix. Match. MagSafe.",
    routeName: 'accessories/all',
    imageUrl: "/images/category/Accessories.JPG",
    items: [
      {
        id: 1,
        name: 'Magic Keyboard with Touch ID',
        imageUrl: '/images/storePages/accessories/magic-keyboard-touch-id.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 2,
        name: 'Magic Mouse',
        imageUrl: '/images/storePages/accessories/magic-mouse.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 3,
        name: 'Magic Trackpad',
        imageUrl: '/images/storePages/accessories/magic-trackpad.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 4,
        name: 'USB-C to USB Adapter',
        imageUrl: '/images/storePages/accessories/usb-c-to-usb-adapter.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 5,
        name: 'Thunderbolt 3 (USB-C) to Thunderbolt 2 Adapter',
        imageUrl: '/images/storePages/accessories/thunderbolt3-to-thunderbolt2.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 6,
        name: 'Apple USB SuperDrive',
        imageUrl: '/images/storePages/accessories/usb-superdrive.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 7,
        name: 'AppleCare+ for MacBook Pro 14-inch',
        imageUrl: '/images/storePages/accessories/applecare-macbook-pro.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 8,
        name: 'Belkin Thunderbolt 4 Dock Pro',
        imageUrl: '/images/storePages/accessories/belkin-thunderbolt-dock.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 9,
        name: 'Pro Display XDR',
        imageUrl: '/images/storePages/accessories/pro-display-xdr.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      },
      {
        id: 10,
        name: 'Apple Thunderbolt Cable (0.8 m)',
        imageUrl: '/images/storePages/accessories/apple-thunderbolt-cable.jpg',
        basePrice: 99,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      }
    ],
  },
  {
    id: 11,
    order: 11,
    title: 'Apple Gift Card',
    motto: "For everything and everyone.",
    routeName: 'shop/gift-cards',
    imageUrl: "/images/category/GiftCard.JPG",
    itemImageUrl: '/images/productPages/giftCard/hero__ernd10zm1dsi_large.JPG',
    items: [
      {
        id: 1,
        name: 'Apple Gift Card',
        imageUrl: '/images/productPages/giftCard/hero__ernd10zm1dsi_large.JPG',
        basePrice: 25,
        giftCard: false,
        giftCardPrice: null,
        newPrice: null,
        newItem: false,
      }
    ],
  }
  // ,
  // {
  //   id: 1,
  //   title: 'Mac',
  //   routeName: 'shop/buy-mac',
  //   motto: "If you can dream it,\nMac can do it.",
  //   imageUrl: "/images/category/Mac.JPG",
  //   videoUrl: "/videos/Mac.mp4",
  // },
  // {
  //   id: 2,
  //   title: 'iPad',
  //   routeName: 'shop/buy-ipad',
  //   motto: "Touch, draw, and type\non one magical device.",
  //   imageUrl: "/images/category/iPad.JPG",
  //   videoUrl: "/videos/iPad.mp4",
  // },
  // {
  //   id: 3,
  //   title: 'iPhone',
  //   routeName: 'shop/buy-iphone',
  //   motto: "Designed to be loved.",
  //   imageUrl: "/images/category/iPhone.JPG",
  //   videoUrl: "/videos/iPhone.mp4",
  // },
  // {
  //   id: 4,
  //   title: 'Apple Watch',
  //   routeName: 'shop/buy-watch',
  //   motto: "To wear it is to love it.",
  //   imageUrl: "/images/category/watch.JPG",
  //   videoUrl: "/videos/watch.mp4",
  // },
  // {
  //   id: 5,
  //   title: 'AirPods',
  //   routeName: 'airpods',
  //   motto: "A magical connection to your devices.",
  //   imageUrl: "/images/category/AirPods.JPG",
  //   videoUrl: "/videos/AirPods.mp4",
  // },
  // {
  //   id: 6,
  //   title: 'AirTag',
  //   routeName: 'airtag',
  //   motto: "A magical connection to your devices.",
  //   imageUrl: "/images/category/AirPods.JPG",
  //   videoUrl: "/videos/AirPods.mp4",
  // },
  // {
  //   id: 7,
  //   title: 'Apple TV 4K',
  //   routeName: 'apple-tv-4k',
  //   imageUrl: "/images/category/TV.JPG",
  //   videoUrl: "/videos/Apple-TV-4K.mp4",
  // },
  // {
  //   id: 8,
  //   title: 'HomePod',
  //   routeName: 'homepod',
  //   motto: "Speakers of the house.",
  //   imageUrl: "/images/category/HomePod.JPG",
  // },
  // {
  //   id: 9,
  //   title: 'Accessories',
  //   routeName: 'accessories/all',
  //   imageUrl: "/images/category/Accessories.JPG",
  // },
  // {
  //   id: 10,
  //   title: 'Apple Gift Card',
  //   motto: "For everything and everyone.",
  //   routeName: 'shop/gift-cards',
  //   imageUrl: "/images/category/GiftCard.JPG",
  //   itemImageUrl: '/images/productPages/giftCard/hero__ernd10zm1dsi_large.JPG',
  // }

];

export default SHOP_DATA;

  // {
  //   id: 1,
  //   title: 'Mac',
  //   routeName: 'shop/buy-mac',
  //   motto: "If you can dream it,\nMac can do it.",
  //   imageUrl: "/images/category/Mac.JPG",
  //   videoUrl: "/videos/Mac.mp4",

  //   items: [
  //     {
  //       id: 1,
  //       name: 'MacBook Air',
  //       imageUrl: '/images/storePages/buyMac/mac-card-40-macbook-air-13-15-202306.JPG',
  //       price: 999,
  //     },
  //     {
  //       id: 2,
  //       name: 'MacBook Pro',
  //       imageUrl: '/images/storePages/buyMac/mac-card-40-macbookpro-14-16-202310_GEO_US.JPG',
  //       price: 1599,
  //     },
  //     {
  //       id: 3,
  //       name: 'iMac',
  //       imageUrl: '/images/storePages/buyMac/mac-card-40-imac-24-202310.JPG',
  //       price: 1299,
  //     },
  //     {
  //       id: 4,
  //       name: 'Mac mini',
  //       imageUrl: 'images/storePages/buyMac/mac-card-40-mac-mini-202301.JPG',
  //       price: 599,
  //     },
  //     {
  //       id: 5,
  //       name: 'Mac Studio',
  //       imageUrl: '/images/storePages/buyMac/mac-card-40-mac-studio-202306.JPG',
  //       price: 1999,
  //     },
  //     {
  //       id: 6,
  //       name: 'Studio Display',
  //       imageUrl: '/images/storePages/buyMac/mac-card-40-studio-display-202203.JPG',
  //       price: 1599,
  //     },
  //     {
  //       id: 7,
  //       name: 'Mac Pro',
  //       imageUrl: '/images/storePages/buyMac/mac-card-40-mac-pro-202306.JPG',
  //       price: 6999,
  //     },
  //     {
  //       id: 8,
  //       name: 'Pro Display XDR',
  //       imageUrl: '/images/storePages/buyMac/mac-card-40-mac-pro-display-202108.JPG',
  //       price: 4999,
  //     }
  //   ],
  // },
  // {
  //   id: 2,
  //   title: 'iPad',
  //   routeName: 'shop/buy-ipad',
  //   motto: "Touch, draw, and type\non one magical device.",
  //   imageUrl: "/images/category/iPad.JPG",
  //   videoUrl: "/videos/iPad.mp4",
  //   items: [
  //     {
  //       id: 1,
  //       name: 'iPad Pro',
  //       imageUrl: '/images/storePages/buyiPad/ipad-card-40-pro-202405.JPG',
  //       price: 999,
  //     },
  //     {
  //       id: 2,
  //       name: 'iPad Air',
  //       imageUrl: '/images/storePages/buyiPad/ipad-card-40-air-202405.JPG',
  //       price: 599,
  //     },
  //     {
  //       id: 3,
  //       name: 'iPad',
  //       imageUrl: '/images/storePages/buyiPad/ipad-card-40-ipad-202405.JPG',
  //       price: 349,
  //     },
  //     {
  //       id: 4,
  //       name: 'iPad mini',
  //       imageUrl: '/images/storePages/buyiPad/ipad-card-40-ipad-mini-202109.JPG',
  //       price: 499,
  //     },
  //   ],
  // },
  // {
  //   id: 3,
  //   title: 'iPhone',
  //   routeName: 'shop/buy-iphone',
  //   motto: "Designed to be loved.",
  //   imageUrl: "/images/category/iPhone.JPG",
  //   videoUrl: "/videos/iPhone.mp4",
    
  //   items: [
  //     {
  //       "id": 1,
  //       "name": "iPhone 16 Pro & iPhone 16 Pro Max",
  //       "imageUrl": "/images/storePages/buyiPhone/iphone-card-40-iphone16prohero-202409.JPG",
  //       "price": 999
  //     },
  //     {
  //       "id": 2,
  //       "name": "iPhone 16 & iPhone 16 Plus",
  //       "imageUrl": "/images/storePages/buyiPhone/iphone-card-40-iphone16hero-202409.JPG",
  //       "price": 799
  //     },
  //     {
  //       "id": 3,
  //       "name": "iPhone 15 & iPhone 15 Plus",
  //       "imageUrl": "/images/storePages/buyiPhone/iphone-card-40-iphone15hero-202309.JPG",
  //       "price": 699
  //     },
  //     {
  //       "id": 4,
  //       "name": "iPhone 14 & iPhone 14 Plus",
  //       "imageUrl": "/images/storePages/buyiPhone/iphone-card-40-iphone14-202209.JPG",
  //       "price": 599
  //     },
  //     {
  //       "id": 5,
  //       "name": "iPhone SE",
  //       "imageUrl": "/images/storePages/buyiPhone/iphone-card-40-iphonese-202203.JPG",
  //       "price": 429
  //     },
  //     {
  //       "id": 6,
  //       "name": "Explore all iPhone accessories",
  //       "imageUrl": "/images/storePages/buyiPhone/iphone-card-40-accessories-202409.JPG",
  //       "price": null
  //     }
  //   ]
  // },
  // {
  //   id: 4,
  //   title: 'Apple Watch',
  //   routeName: 'shop/buy-watch',
  //   motto: "To wear it is to love it.",
  //   imageUrl: "/images/category/watch.JPG",
  //   videoUrl: "/videos/watch.mp4",
  //   items: [
  //     {
  //       id: 1,
  //       name: 'Apple Watch Series 10',
  //       imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-s10-202409.JPG',
  //       price: 399,
  //     },
  //     {
  //       id: 2,
  //       name: 'Apple Watch Ultra 2',
  //       imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-ultra2-202409.JPG',
  //       price: 799,
  //     },
  //     {
  //       id: 3,
  //       name: 'Apple Watch SE',
  //       imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-se-202409.JPG',
  //       price: 249,
  //     },
  //     {
  //       id: 4,
  //       name: 'Apple Watch Hermès Series 10',
  //       imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-hermes-202409.JPG',
  //       price: 1249,
  //     },
  //     {
  //       id: 5,
  //       name: 'Apple Watch Hermès Ultra 2',
  //       imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-hermes-ultra-202409.JPG',
  //       price: 1399,
  //     },
  //     {
  //       id: 6,
  //       name: 'Explore all Apple Watch accessories.',
  //       imageUrl: '/images/storePages/buyAppleWatch/watch-card-40-acc-202409.JPG',
  //       price: 1399,
  //     },
  //   ],
  // },
  // {
  //   id: 5,
  //   title: 'Apple Vision Pro',
  //   routeName: 'shop/buy-vision',
  //   items: [
  //     {
  //       id: 1,
  //       name: 'Apple Vision Pro',
  //       imageUrl: '/images/storePages/buyVisionPro/vision-pro-card-66-vision-pro-202401.JPG',
  //       price: 3499,
  //     },
  //     {
  //       id: 2,
  //       name: 'ZEISS Optical Inserts',
  //       imageUrl: '/images/storePages/buyVisionPro/vision-pro-card-40-zeiss-optical-202401.JPG',
  //       price: 99,
  //     },
  //     {
  //       id: 3,
  //       name: 'Explore all Vision Pro accessories.',
  //       imageUrl: '/images/storePages/buyVisionPro/vision-pro-card-40-accessories-202401.JPG',
  //       price: null,
  //     }
  //   ],
  // },
  // {
  //   id: 6,
  //   title: 'AirPods',
  //   routeName: 'airpods',
  //   motto: "A magical connection to your devices.",
  //   imageUrl: "/images/category/AirPods.JPG",
  //   videoUrl: "/videos/AirPods.mp4",
  //   items: [
  //     {
  //       id: 1,
  //       name: 'AirPods 4',
  //       imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
  //       price: 129,
  //     },
  //     {
  //       id: 2,
  //       name: 'AirPods 4',
  //       imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
  //       price: 179,
  //     },
  //     {
  //       id: 3,
  //       name: 'AirPods Pro 2',
  //       imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
  //       price: 249,
  //     },
  //     {
  //       id: 4,
  //       name: 'AirPods Max',
  //       imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
  //       price: 549,
  //     }
  //   ],
  // },
  // {
  //   id: 7,
  //   title: 'AirTag',
  //   routeName: 'airtag',
  //   motto: "A magical connection to your devices.",
  //   imageUrl: "/images/category/AirPods.JPG",
  //   videoUrl: "/videos/AirPods.mp4",
  //   routeName: 'airpods',
  //   items: [
  //     {
  //       id: 30,
  //       name: 'Camo Down Vest',
  //       imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
  //       price: 325,
  //     },
  //     {
  //       id: 31,
  //       name: 'Floral T-shirt',
  //       imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
  //       price: 20,
  //     },
  //     {
  //       id: 32,
  //       name: 'Black & White Longsleeve',
  //       imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
  //       price: 25,
  //     },
  //     {
  //       id: 33,
  //       name: 'Pink T-shirt',
  //       imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
  //       price: 25,
  //     },
  //     {
  //       id: 34,
  //       name: 'Jean Long Sleeve',
  //       imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
  //       price: 40,
  //     },
  //     {
  //       id: 35,
  //       name: 'Burgundy T-shirt',
  //       imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
  //       price: 25,
  //     },
  //   ],
  // },
  // {
  //   id: 8,
  //   title: 'Apple TV 4K',
  //   routeName: 'apple-tv-4k',
  //   motto: "A magical connection to your devices.",
  //   imageUrl: "/images/category/AirPods.JPG",
  //   videoUrl: "/videos/Apple-TV-4K.mp4",
  //   items: [
  //     {
  //       id: 1,
  //       name: 'Camo Down Vest',
  //       imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
  //       price: 325,
  //     }
  //   ],
  // },
  // {
  //   id: 8,
  //   title: 'HomePod',
  //   routeName: 'homepod',
  //   motto: "Speakers of the house.",
  //   imageUrl: "/images/category/AirPods.JPG",
  //   items: [
  //     {
  //       id: 1,
  //       name: 'HomePod',
  //       price: 299,
  //     },
  //     {
  //       id: 2,
  //       name: 'HomePod MINI',
  //       price: 99,
  //     }
  //   ],
  //   itemImageUrl: '/images/productPages/hero__ernd10zm1dsi_large.JPG',
  // },
  // {
  //   id: 9,
  //   title: 'Accessories',
  //   routeName: 'accessories/all',
  //   imageUrl: "/images/category/Accessories.JPG",
  //   items: [
  //     {
  //       id: 1,
  //       name: 'Magic Keyboard with Touch ID',
  //       imageUrl: '/images/storePages/macAccessories/magic-keyboard-touch-id.jpg',
  //       price: 149,
  //     },
  //     {
  //       id: 2,
  //       name: 'Magic Mouse',
  //       imageUrl: '/images/storePages/macAccessories/magic-mouse.jpg',
  //       price: 99,
  //     },
  //     {
  //       id: 3,
  //       name: 'Magic Trackpad',
  //       imageUrl: '/images/storePages/macAccessories/magic-trackpad.jpg',
  //       price: 149,
  //     },
  //     {
  //       id: 4,
  //       name: 'USB-C to USB Adapter',
  //       imageUrl: '/images/storePages/macAccessories/usb-c-to-usb-adapter.jpg',
  //       price: 19,
  //     },
  //     {
  //       id: 5,
  //       name: 'Thunderbolt 3 (USB-C) to Thunderbolt 2 Adapter',
  //       imageUrl: '/images/storePages/macAccessories/thunderbolt3-to-thunderbolt2.jpg',
  //       price: 49,
  //     },
  //     {
  //       id: 6,
  //       name: 'Apple USB SuperDrive',
  //       imageUrl: '/images/storePages/macAccessories/usb-superdrive.jpg',
  //       price: 79,
  //     },
  //     {
  //       id: 7,
  //       name: 'AppleCare+ for MacBook Pro 14-inch',
  //       imageUrl: '/images/storePages/macAccessories/applecare-macbook-pro.jpg',
  //       price: 279,
  //     },
  //     {
  //       id: 8,
  //       name: 'Belkin Thunderbolt 4 Dock Pro',
  //       imageUrl: '/images/storePages/macAccessories/belkin-thunderbolt-dock.jpg',
  //       price: 399,
  //     },
  //     {
  //       id: 9,
  //       name: 'Pro Display XDR',
  //       imageUrl: '/images/storePages/macAccessories/pro-display-xdr.jpg',
  //       price: 4999,
  //     },
  //     {
  //       id: 10,
  //       name: 'Apple Thunderbolt Cable (0.8 m)',
  //       imageUrl: '/images/storePages/macAccessories/apple-thunderbolt-cable.jpg',
  //       price: 39,
  //     }
  //   ],
  // },
  // {
  //   id: 10,
  //   title: 'Apple Gift Card',
  //   motto: "For everything and everyone.",
  //   routeName: 'shop/gift-cards',
  //   imageUrl: "/images/category/GiftCard.JPG",
  //   itemImageUrl: '/images/productPages/giftCard/hero__ernd10zm1dsi_large.JPG',
  // }